### ISSUE TITLE
A question about your model.pth.tar

### ISSUE THREAD

**Issue by zzt941006** [arnoweng/CheXNet#1]
When I download model.pth.tar,I can't unzip.
An error shows: data has been destroyed。

**Comment by arnoweng** [comment]
The file model.pth.tar is named by a .tar suffix according to the custom of Pytorch community, and it can not be decompressed. 
You can load the model and print detailed information in the program if you want to see the structure and parameters of this model.

**Comment by arnoweng** [comment]
@zzt941006 
The file model.pth.tar is named by a .tar suffix according to the custom of Pytorch community, and it can not be decompressed.
You can load the model and print detailed information in the program if you want to see the structure and parameters of this model.

**Comment by pyaf** [comment]
lol, I thought it was a tar file. (it shouldn't have been named as such though, .pth is enough)
