### ISSUE TITLE
module 'torchvision.transforms' has no attribute 'Resize'

### ISSUE THREAD

**Issue by z744364418p** [arnoweng/CheXNet#17]
module 'torchvision.transforms' has no attribute 'Resize',这个怎么解决

**Comment by arnoweng** [comment]
Several versions of torchvision.transforms do not include Resize. Try updating your torchvision.

**Comment by aayushkumarjvs** [comment]
transforms.Resize(256)
AttributeError: module 'torchvision.transforms' has no attribute 'Resize'
 transforms.TenCrop(224), 
AttributeError: module 'torchvision.transforms' has no attribute 'TenCrop'
It's basically the same error. I was using torchvision 0.3.0 which showed this error.
After which I uninstalled and used torchvision 0.2.0
Could you help in which version of torchvision should I be using this?

**Comment by arnoweng** [comment]
@aayushkumarjvs Clone this latest [transforms.py](https://github.com/pytorch/vision/blob/master/torchvision/transforms/transforms.py), place it in your own project and import it manually.

**Comment by Yonggie** [comment]
I can use torchvision0.1.x but can not use torchvision0.3.x, it keeps showing error: ImportError: DLL load failed: can't find module
