### ISSUE TITLE
Model not working on Real Life Xrays

### ISSUE THREAD

**Issue by bijoygit** [arnoweng/CheXNet#18]
I have couple of frontal chest x rays which I know have disease. But when I predict it with the model, it shows very less probability for all the 14 diseases.

It doesn't seem to work on real life X-rays

Please help

**Comment by arnoweng** [comment]
The model was trained on ChestX-ray14, if you want to transfer it to fit another data set, you need to fine-tune this model.

**Comment by bijoygit** [comment]
how should I define the colours on the final output. Which color denotes an abnormality

**Comment by Akhiladdh** [comment]
@bijoygit I want to use this model to predict on custom data.
Can you please let me know how you used it to do the same?
Thank you.
