### ISSUE TITLE
How to create the heatmap

### ISSUE THREAD

**Issue by mengquann** [arnoweng/CheXNet#3]
Your work is good.
I want to know how to create the heatmap. Now the "output" variable in the code is a 10*14 mat, and it seems not the heatmap.

**Comment by arnoweng** [comment]
@mengquann Get feature maps from the last conv layer. You can refer [this paper](https://arxiv.org/abs/1512.04150) for more details.

**Comment by smivv** [comment]
@arnoweng could you please provide the code how you do that?

**Comment by taewookim** [comment]
ditto @smivv 
any code that can be shared?

**Comment by arnoweng** [comment]
@smivv @taewookim You can adapt the author's [code](https://github.com/metalbubble/CAM) as needed.
