### ISSUE TITLE
Where can i configure GPU details?

### ISSUE THREAD

**Issue by Akhiladdh** [arnoweng/CheXNet#30]

**Comment by Akhiladdh** [comment]
I want to use multiple GPUs where can i configure those details?

**Comment by arnoweng** [comment]
@Akhiladdh The code can be directly used for training on multiple GPUs. You just need to specify available GPU IDs (e.g. _CUDA_VISIBLE_DEVICES=0,1,2,3 python model.py_).

**Comment by Akhiladdh** [comment]
@arnoweng Thank you so much. Can you add details about how to retrain this?

**Comment by arnoweng** [comment]
@Akhiladdh We followed the training strategy described in the official paper. Sorry the training code is not available yet.

**Comment by Akhiladdh** [comment]
Thank you!
