### ISSUE TITLE
Keras implementation?

### ISSUE THREAD

**Issue by taewookim** [arnoweng/CheXNet#6]
Anyone know if there's a keras implementation of chexnet?

**Comment by brucechou1983** [comment]
@taewookim maybe you will be interested in [my implementation](https://github.com/brucechou1983/CheXNet-Keras ).

**Comment by taewookim** [comment]
hey @brucechou1983 . Thanks for that!
Curious.. how does the keras version compare to pytorch version ? comparable? Any particular issues you noticed?

**Comment by brucechou1983** [comment]
@taewookim Please check [this issue](https://github.com/brucechou1983/CheXNet-Keras/issues/1).

**Comment by alyato** [comment]
hi,@taewookim 
I have one question about cheXnet-keras from @brucechou1983 .
Do you check it [`https://github.com/brucechou1983/CheXNet-Keras/issues/32`](url)
Thanks.
